AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Hello World AWS Lambda and Amazon API Gateway REST API
  Sample AWS SAM template to create a simple Lambda function connected to a REST API.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # Increased timeout to accommodate external HTTP calls with network latency
    # External service calls may take longer than 3 seconds
    Timeout: 10
    # Explicit memory allocation (affects CPU allocation proportionally)
    # 256 MB provides adequate resources for this simple function
    MemorySize: 256

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64  # Using ARM64 for cost efficiency (up to 20% cheaper than x86_64)
      # Environment variables for configuration
      # Allows easy testing with mock services or different endpoints
      Environment:
        Variables:
          # Optional: Override the default checkip service URL
          # Example: CHECKIP_URL: "http://checkip.amazonaws.com/"
          # Leave unset to use default in code
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            # Add OPTIONS method for CORS preflight support
            Cors:
              AllowMethods: "'GET,OPTIONS'"
              AllowHeaders: "'Content-Type'"
              AllowOrigin: "'*'"  # In production, specify your frontend domain

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn